{% set name = "hipscat" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/astronomy-commons/hipscat/archive/v{{ version }}.tar.gz
  sha256: ada1618a1a3a3be02341b48d74b36c67bb73524546a3cb10873e5ee5d14458a2
# curl -L https://github.com/astronomy-commons/hipscat/archive/v0.2.1.tar.gz | openssl sha256

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=62
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.9
    - astropy
    - fsspec <=2023.9.2
    - healpy
    - numba
    - pandas
    - pyarrow >=10.0.0
    - typing-extensions >=4.3.0
    - spherical-geometry

test:
  imports:
    - hipscat
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/astronomy-commons/hipscat
  summary: 'A HiPSCat astronomical catalog format reader library'
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mjuric
